name = "taptempo"
version = "1.0.0"
license = "GPL-3.0-or-later"
author = "Vincent Magnin and the Fortran-lang community"
maintainer = "Vincent Magnin"
copyright = "Copyright 2021"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
